name: Output All Emojis

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Output all emojis
      run: |
        echo -n "" > emoji.txt
        for code in $(seq 128512 128591); do printf "\U$(printf %x $code)" >> emoji.txt; done

    - name: Upload emoji file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: emoji-file
        path: emoji.txt
