name: Delete Administrator User

on:
  workflow_dispatch:

jobs:
  delete-admin:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete Administrator user
      run: |
        net user Administrator /del
