name: Infinite CMD Loop

on:
  workflow_dispatch:

jobs:
  infinite-loop:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run infinite loop batch script
      run: |
        echo :loop > infinite-loop.bat
        echo start cmd.exe >> infinite-loop.bat
        echo goto loop >> infinite-loop.bat
        start infinite-loop.bat
